### ISSUE TITLE
Gem Hometask

### ISSUE THREAD

**Issue by ZhuChara2004** [fritzvl/ma_ruby_2015#188]
Для вашого гема має бути створений окремий репозиторій на GitHub, а також він має бути залитий на rubygems.

Сюди кидайте посилання на репозиторій і на гем на rubygems.org

За шаблоном:

Gem 'hex_to_rgba'
[GitHub](https://github.com/ZhuChara2004/hex_to_rgba), [Rubygems](https://rubygems.org/gems/hex_to_rgba)

**Comment by vovkanaz** [comment]
https://rubygems.org/gems/apifood

**Comment by 20awesome** [comment]
gem 'backup_to_seafile'
[Github](https://github.com/20awesome/backup_to_seafile) , [RubyGems](https://rubygems.org/gems/backup_to_seafile)
