### ISSUE TITLE
Перенесення занять.

### ISSUE THREAD

**Issue by ZhuChara2004** [fritzvl/ma_ruby_2015#192]
В зв'язку з великою кількістю захворівших людей, з метою неросповсюдження хвороб, заняття цього тижня (19 і 21 січня 2015р) проводитися не будуть. Щодо наступного тижня - буде зрозуміло пізніше.

**Comment by shcherb** [comment]
ok

**Comment by NicholasBin** [comment]
Ok

**Comment by NovitskyiDA** [comment]
ok
