### ISSUE TITLE
Лекція 14.3

### ISSUE THREAD

**Issue by ZhuChara2004** [fritzvl/ma_ruby_2015#197]
### MA Ruby 2015 Lection 14.3 - ActiveAdmin
-----------------------------------

Так як я хворію, в нас сьогодні буде експериментальна лекція. Я записав скрінкаст, ви його подивіться, і питання які виникають, постіть в цей іш'ю.

Тема лекції – [ActiveAdmin](https://github.com/activeadmin/activeadmin). Це - фреймворк, що використовується, коли потрібно швидко зробити щось типу бекенду для адміністрування бази даних.

-----------------------------------

### Скрінкаст
[![Lection 14.3](http://img.youtube.com/vi/SCBg2kqAOEs/0.jpg)](https://www.youtube.com/watch?v=SCBg2kqAOEs)

-----------------------------------

### Домашнє завдання

* прикрутити до проекта  ActiveAdmin
* винести туди менеджмент постів (якщо ви робите блог)
* *додаткове* підключити діскас для коментарів (якщо ви робите блог)

**Comment by shcherb** [comment]
ок, принято
