### ISSUE TITLE
Project #1 - Media aggregator

### ISSUE THREAD

**Issue by kokosko** [fritzvl/ma_ruby_2015#61]
Members:
- [Natasha Pavlenko](https://github.com/Noli29)
- [Oleh Holovin](https://github.com/deathliger666)
- [Vasya Shevchenko](https://github.com/Jack-888)
- [Kostya Doletskiy](https://github.com/kokosko)

**Comment by Noli29** [comment]
я на 1 проекте

**Comment by deathliger666** [comment]
I`m here

**Comment by Jack-888** [comment]
Hi! I'm on this project.
Skype: vasya.shevchenko
e-mail:  vasya.shevchenko.2011@gmail.com

**Comment by kokosko** [comment]
hi everyone! 
kostyaha
kostya.kokosko@gmail.com
welcome!

**Comment by Noli29** [comment]
Skype: natasha.noelka
e-mail: noli.pogorelova@gmail.com

**Comment by ZhuChara2004** [comment]
До вівторка вирішіть хто в якій команді...

**Comment by kokosko** [comment]
що означає "Хто в якій команаді?" Ті, що тут відписалися - ті в команді проекту №1, хіба не так?

**Comment by ZhuChara2004** [comment]
Думаю, тут буде дві команди. Якщо більше ніхто не відпишеться - працюйте з тими, хто відписався на зараз. Це і буде ваша команда.

**Comment by vadia007** [comment]
Skype: vadia007

**Comment by deathliger666** [comment]
пропоную в неділю о 21.00 зв'язатися в скайпі щодо написання gem-а
