### ISSUE TITLE
Home tasks

### ISSUE THREAD

**Issue by ZhuChara2004** [fritzvl/ma_ruby_2015#70]
* 2015.10.29 Lection 2 - Abstracts
  * Зробити аналіз предметної області з використанням обговорюваних на лекції паттернів проєктування (при бажанні, використати markdown)
  * Відмітитись в issue, який відповідає вашому проекту
* 2015.11.05 Lection 3 - Ruby basics
 * написати програму на рубі, яка відповідає вашому аналізу предметної області – створити класи, описати методи цих класів
* 2015.11.12 Lection 4 - Collections
 * написати довільну програму на рубі, яка використовує колекції

**Comment by powerbot15** [comment]
Есть предложение описывать предметную область сразу в рамках предстоящего проекта. Думаю будет полезно уже сейчас проработать базис для успешной разработки выпускного приложения

**Comment by fritzvl** [comment]
Слушна думка щодо предметної області. 

* 2015.11.19 Lection 5 - Mastering Ruby objects  
  *  Для власної предметної області, як варіант, використовуючи класи з домашнього завдання 3, написати код, який буде динамічно змінювати властивості об'єкта. А також будуть використані модулі та едементи мета-програмування.

**Comment by fritzvl** [comment]
Домашнє завдання по ітогах лекції 5-5.1:

Є умовна відповідь сервера із структурою наведеною нижче:
RESPONSE='{"person":{"personal_data":{"name": "John Smith", "gender":"male", "age":56 ......},"social_profiles":["http://facebook....","http://twitter...","http://", .... ],"additional_info":{"hobby":["pubsurfing","drinking","hiking"...], "pets":[{"name":"Mittens","species":"Felis silvestris catus"},],...}}'

Завдання - написати клас, який би приймав на вході подібну строку, а на виході віддава об'єкт Person, який би адаптувався до структури даних яка йому віддається.
Що мається на увазі під адаптацією. Ми знаємо, що повертаються персональні дані користувача, подумайте які то можуть бути дані, наприклад список ймовірних соціальних профілів у користувача досить обмежений, варіантів яких тварин тримає людина також більш-менш обмежений, а екзотичні можуть бути кваліфіковані як "exotic".
Тож завдання полягає в тому, щоб на основі цього джейсона побудувати клас Builder, який би створював потрібний нам об'єкт використовуючи в тому числі метрапрограмування та міксіни. 

Приклади методів:

adult? - відповідає так чи ні з огляду на вік
twitter_account? - відповідно залежно від наявності посилання на профайл твіттера
have_hobbies? - відповідно до того чи є в профайлі хоббі
Результатом має бути виведення профайла у текстовому відформатованому вигляді, із застосуванням всіх методів які були динамічно визначені.

Ну і інші ознаки які ви можете придумати для людини також опишіть.
